---
meta:
  concourse:
  - test-failure: &test-failure
      timeout: 10m
      input_mapping: { source: pull-request, common-tasks: pull-request }
      on_success:
        put: pull-request
        params: {path: pull-request, status: failure}
  - test-success: &test-success
      timeout: 10m
      input_mapping: { source: pull-request, common-tasks: pull-request }
      on_failure:
        put: pull-request
        params: {path: pull-request, status: failure}

groups:
  - name: PR
    jobs:
    - test-it

jobs:
  - name: test-it
    plan:
    - aggregate:
      - get: pull-request
        trigger: true
        version: every
    - put: pull-request
      params: {path: pull-request, status: pending}
    - aggregate:
      - task: terraform-0.11.1-success
        <<: *test-success
        file: pull-request/terraform/0.11.1.yml
        params:
          command: test
          cache: true
          directories: |
            terraform/test/success
      - try:
          task: terraform-0.10.8-failure
          <<: *test-failure
          file: pull-request/terraform/0.11.1.yml
          params:
            command: test
            cache: true
            directories: |
              terraform/test/failure

      - task: terraform-0.10.8-success
        <<: *test-success
        file: pull-request/terraform/0.10.8.yml
        params:
          command: test
          cache: true
          directories: |
            terraform/test/success
      - try:
          task: terraform-0.10.8-failure
          <<: *test-failure
          file: pull-request/terraform/0.10.8.yml
          params:
            command: test
            cache: true
            directories: |
              terraform/test/failure

    - put: pull-request
      params: {path: pull-request, status: success}

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: telia-oss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 30s
    source:
      repository: telia-oss/concourse-tasks
      access_token: ((github-access-token))
